version: 2

defaults: &defaults
  working_directory: /go/src/github.com/weaveworks/scope
  docker:
    - image: weaveworks/scope-backend-build:master-fda40b83

client-defaults: &client-defaults
  working_directory: /home/weave/scope
  docker:
    - image: weaveworks/scope-ui-build:master-fda40b83

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - lint
      - unit-test
      - client-build
      - client-test:
          requires:
            - client-build
      - xplatform-build:
          requires:
            - build
      - build:
          requires:
            - client-build
      - integration-tests:
          requires:
            - lint
            - unit-test
            - build
      - deploy:
          filters:
            branches:
              only: staging
          requires:
            - client-test
            - integration-tests

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: make BUILD_IN_CONTAINER=false lint

  unit-test:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout


      - run: COVERDIR=./coverage make BUILD_IN_CONTAINER=false CODECGEN_UID=23 tests
      - persist_to_workspace:
          root: .
          paths:
          - coverage

  # Create client/build/index.html
  client-build:
    <<: *client-defaults
    steps:
      - checkout
      # Convoluted set of steps here to mimic Makefile actions of bind-mounting different dirs into container
      - run: mv client/app /home/weave/
      - run: cd /home/weave; mkdir build         ; yarn run build         ; mv build          scope/client
      - run: cd /home/weave; mkdir build-external; yarn run build-external; mv build-external scope/client
      - run: cd /home/weave; mkdir tmp           ; yarn run bundle        ; mv tmp            scope
      - persist_to_workspace:
          root: /home/weave/scope
          paths:
          - client/build/
          - client/build-external/
          - tmp/weave-scope.tgz

  client-test:
    <<: *client-defaults
    steps:
      - checkout
      - run: |
          mv client/app client/test /home/weave/
          cd /home/weave; yarn run lint
          cd /home/weave; yarn test

  xplatform-build:
    <<: *defaults
    steps:
      - checkout
      - run: GOARCH=arm  make BUILD_IN_CONTAINER=false GO_BUILD_INSTALL_DEPS= prog/scope
      - run: GOOS=darwin make BUILD_IN_CONTAINER=false GO_BUILD_INSTALL_DEPS= prog/scope

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: make BUILD_IN_CONTAINER=false SUDO= static all
      - run: cd extras; make BUILD_IN_CONTAINER=false
      - run: make -C tools/runner
      - persist_to_workspace:
          root: .
          paths:
          - scope.tar
          - cloud-agent.tar
          - tools/runner/runner
          - prog/externalui/
          - prog/staticui/
          - report/report.codecgen.go
          - render/detailed/detailed.codecgen.go

  integration-tests:
    machine:
      image: circleci/classic:201709-01
    working_directory: /home/circleci/src/github.com/weaveworks/scope
    environment:
      CIRCLE_ARTIFACTS: /tmp/artifacts
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      GOPATH: /home/circleci/
    parallelism: 2
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          sudo apt-get update
          sudo apt-get install python-pip jq pv
      - run: mkdir $CIRCLE_ARTIFACTS
      # kick off creation of test VM
      - run: test -z "$SECRET_PASSWORD" || bin/setup-circleci-secrets "$SECRET_PASSWORD"
      - run: test -z "$SECRET_PASSWORD" || (cd integration; ./gce.sh make_template)
      - run: test -z "$SECRET_PASSWORD" || (cd integration; ./gce.sh setup && eval $(./gce.sh hosts); ./setup.sh)
      - run: make deps; touch tools/runner/runner
      # Run all integration tests
      - run:
          command: test -z "$SECRET_PASSWORD" || (cd integration; eval $(./gce.sh hosts); ./run_all.sh)
          no_output_timeout: 5m
      # Destroy testing VMs:
      - run:
          command: test -z "$SECRET_PASSWORD" || (cd integration; ./gce.sh destroy)
          background: true
      # Code coverage
      - run: ./tools/cover/gather_coverage.sh ./coverage
      - run: goveralls -repotoken $COVERALLS_REPO_TOKEN -coverprofile=profile.cov -service=circleci
      - run: cp coverage.* */*.codecgen.go $CIRCLE_ARTIFACTS
      - store_artifacts:
          path: /tmp/artifacts

  deploy:
    <<: *defaults
    environment:
      IMAGES: scope cloud-agent
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: |
          pip install awscli
          docker load -i scope.tar
          docker load -i cloud-agent.tar
      - run: |
          test -z "${DOCKER_USER}" && exit 0
          docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
          for IMAGE in $IMAGES; do
              docker tag weaveworks/scope:latest openebs/scope:latest
              docker push openebs/scope:latest
          done
